### PR TITLE
Mitigate chests from spawning in air

### PR DESCRIPTION
**Pull request by XDleader555**
Prevent the chest from spawning on certain blocks (Like grass paths)
if it's within our radius. Modify method for easy changing in the future.

### CODE REVIEW

**Comment by mfnalex** [comment]
Thanks for all the PRs :) I will add a few other stings and then finally release a new version. Would you like to be credited as contributor at SpigotMC? :)

**Comment by XDleader555** [comment]
> Thanks for all the PRs :) I will add a few other stings and then finally release a new version. Would you like to be credited as contributor at SpigotMC? :)

Sure, that'd be cool. I have more features which players on my server wanted which may make it over as PRs.

**Comment by mfnalex** [comment]
Okay, the next update will be released today probably :)

What other features did you add? Unfortunately I changed some stuff and moved files so I don‘t know if it‘s easily possible to merge commits from your fork anymore :/

**Comment by mfnalex** [comment]
Your Spigot username is the same as here?

**Comment by XDleader555** [comment]
Same username. Only things I haven't submitted is instead of teleporting to the chest, the chest can be teleported to the player and remove curse of vanishing items. I can handle merging with your code.

**Pull request merged**
