### PR TITLE
acfetch command

### PR DESCRIPTION
**Pull request by XDleader555**
Bring the chest to the player. Useful if we don't want to teleport players.
Usage /acfetch <chest number>

### CODE REVIEW

**Comment by XDleader555** [comment]
Better integrated with existing commands and polished up the rest of the plugin while I was at it.

**Comment by mfnalex** [comment]
Can I trust you that you tested it properly? :P If so I will release this right away

**Comment by XDleader555** [comment]
I've been running acfetch on my server for a while. I tested the other commits I made on a test server for basic functionality. The only bug I saw was the config doesn't automatically add the new options I added.

**Comment by mfnalex** [comment]
Did you adjust the config-version in the default config.yml and in the Main class?

**Comment by XDleader555** [comment]
Ah I missed version update in the main class

**Comment by mfnalex** [comment]
Thanks for the PR, I will release this as snapshot version because I don't have time right now to update the description at SpigotMC

**Comment by mfnalex** [comment]
**Oh no!** This breaks the chest for me when using fetch when the material is not set to chest. The hologram disappears, and the chest becomes a regular empty chest although it was a custom player head beforehand. Can you reproduce this?

**Comment by mfnalex** [comment]
I don't have time right now to fix this, so it will take a couple of days until I get this done. If you have time, I would be happy if you could create another PR with a fix :)

Also maybe we should move the facing-stuff into a Utils class and replace the if's with a switch/case.

**Comment by XDleader555** [comment]
I'll check that later today and submit another pr

**Comment by mfnalex** [comment]
Unfortunately, this (or the /aclist command) breaks 1.12 compatability.

```
[15:16:05 WARN]: [AngelChest] Task #33 for AngelChest v2.8.0-SNAPSHOT generated an exception
java.lang.NoClassDefFoundError: org/bukkit/block/data/BlockData
        at de.jeff_media.AngelChest.PlayerListener$1.run(PlayerListener.java:123) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.ClassNotFoundException: org.bukkit.block.data.BlockData
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:105) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
        ... 8 more

```

I am not sure what's the problem.

**Comment by XDleader555** [comment]
1.12 handles rotation differently. I'll try submitting a PR to catch that exception and skip rotation if the version can't handle it.

**Comment by mfnalex** [comment]
sorry, I forgot to mention, I already fixed that by moving the methods using BlockData into its own class, and calling those methods with a try catch(Throwable t) :)

**Pull request merged**
